name: Continuous deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - uses: actions-rs/toolchain@v1
      #   with:
      #     profile: minimal
      #     toolchain: stable
      #     override: true

      # - name: Install libudev
      #   run: sudo apt update && sudo apt install libudev-dev

      # - name: Build with cargo-web
      #   run: cargo install cargo-web && cargo web deploy

      - name: Build dummy
        run: touch ./target/deploy/dank.cheese

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: akc8012/QuickballWeb
          publish_dir: ./target/deploy
