name: Continuous deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install libudev
        run: sudo apt update && sudo apt install libudev-dev

      - name: Install cargo-web
        uses: actions-rs/cargo@v1
        with:
          command: cargo install cargo-web

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: cargo web build
          args: --features stdweb
